name: rydem
description: A Flutter app for BLE throttle-to-engine-sound simulation.
publish_to: 'none' # do not publish

version: 1.0.0+1

environment:
  sdk: "3.8.1"
dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/rydem_logo.png     # your logo (square, 1024x1024 ideal)
  adaptive_icon_foreground: assets/images/rydem_logo.png  # transparent FG (512–1024px)
  adaptive_icon_background: "#000000"          # or a bg image: assets/images/rydem_icon_bg.png
  min_sdk_android: 21


dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^7.1.1
  url_launcher: ^6.2.5
  permission_handler: ^12.0.1
  lottie: ^2.2.0
  # BLE
  flutter_reactive_ble: ^5.0.2

  # Audio engine
  just_audio: ^0.10.4
  spotify_sdk: ^3.0.2
  flutter_volume_controller: ^1.1.2
  rxdart: ^0.27.7
  #perfect_volume_control: ^1.0.5   # for system media volume (Android best; iOS limited)
  dio: ^5.5.0

  # simple mic recording
  uuid: ^4.5.1
  archive: ^3.5.1
  record: ^5.0.6

  # State management
  provider: ^6.0.5

  # Gauges
  syncfusion_flutter_gauges: ^20.2.43

  # QR code activation
  #mobile_scanner: ^2.0.0

  # Firebase (for auth, analytics)
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  shared_preferences: ^2.5.3
  # In-app purchases (RevenueCat)
  purchases_flutter: ^8.10.5

  # Cupertino icons
  cupertino_icons: ^1.0.8
  sleek_circular_slider: ^2.1.0
  http: any
  path_provider: any
  audio_session: any


dependency_overrides:
  record_platform_interface: ^1.4.0
  record_linux: ">=0.7.3"   # ensures a version that implements startStream
flutter:
  uses-material-design: true

  # Custom font for futuristic theme
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf

  # Sound assets (uncomment and add more profiles as you create them)
  assets:
    - assets/sounds/default/exhaust.mp3
    - assets/music/demo_song.mp3
    - assets/lottie/splash.json
    - assets/lottie/splash.webm
    - assets/catalog.json
    - assets/images/rydem_logo.png
    # - assets/sounds/sport/idle.mp3
    # - assets/sounds/sport/mid.mp3
    # - assets/sounds/sport/high.mp3
    # - assets/sounds/sport/cutoff.mp3

