// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvl91LZ90pnBghEnGJOoEJass3GAn4dLU',
    appId: '1:276432678868:web:3dfb028da9bda5e2e8f041',
    messagingSenderId: '276432678868',
    projectId: 'rydemdb-e02aa',
    authDomain: 'rydemdb-e02aa.firebaseapp.com',
    storageBucket: 'rydemdb-e02aa.firebasestorage.app',
    measurementId: 'G-DN5Z83YXXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzLjOtZGNNW0H6Xd2JpBkWN7Wsp4i7cUg',
    appId: '1:276432678868:android:6743d2455fb0a197e8f041',
    messagingSenderId: '276432678868',
    projectId: 'rydemdb-e02aa',
    storageBucket: 'rydemdb-e02aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVN00vEirt1mGxewQEEguFobZdlheXCRw',
    appId: '1:276432678868:ios:2c1f4425ab3a31b2e8f041',
    messagingSenderId: '276432678868',
    projectId: 'rydemdb-e02aa',
    storageBucket: 'rydemdb-e02aa.firebasestorage.app',
    iosBundleId: 'com.example.rydem',
  );

}